# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
        # Cache dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm  # Cache the npm cache directory
          key: ${{ runner.os }}-npm
          restore-keys: |
            ${{ runner.os }}-npm
                    
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: .
    
     
